// Created by Crowbar 0.74

$modelname "weapons/w_hopwire.mdl"

$bodygroup "Body"
{
	studio "w_hopwire.smd"
}

$include "w_hopwire_lod.qci"

$surfaceprop "metal"

$contents "solid"

$illumposition 0 0 0

$cdmaterials "models\weapons\V_hopwire\\"

// $include "w_hopwire_box.qci"

$include "w_hopwire_animation.qci"

$include "w_hopwire_collision.qci"

$KeyValues
{
	prop_data 
	{
		"base" "metal.small"
	}
}
